insert into bodyparts (name) values ('neck');
insert into bodyparts (name) values ('shoulders');
insert into bodyparts (name) values ('back');
insert into bodyparts (name) values ('hips');
insert into bodyparts (name) values ('legs');
insert into bodyparts (name) values ('chest');
insert into bodyparts (name) values ('core');

insert into poses (name, sanskrit, demo, difficulty) values ('Downward Facing Dog', 'Adho Mukha Svanasana', 'https://www.youtube.com/embed/j97SSGsnCAQ', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Warrior I', 'Virabhadrasana I', 'https://www.youtube.com/embed/5rT--p_cLOc', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Warrior II', 'Virabhadrasana II', 'https://www.youtube.com/embed/4Ejz7IgODlU', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Warrior III', 'Virabhadrasana III', 'https://www.youtube.com/embed/HuETB2HA2FM', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Reverse Warrior', 'Viparita Virabhadrasana', 'https://www.youtube.com/embed/h_iHFVf-1J4', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Humble Warrior', 'Baddha Virabhadrasana', 'https://www.youtube.com/embed/fXujuk3RIxk', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Triangle', 'Trikonasana', 'https://www.youtube.com/embed/upFYlxZHif0', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Extended Side Angle', 'Utthita Parsvakonasana', 'https://www.youtube.com/embed/0lfzG9jH6cM', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Forward Fold', 'Uttanasana', 'https://www.youtube.com/embed/g7Uhp5tphAs', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Halfway Lift', 'Ardha Uttanasana', 'https://www.youtube.com/embed/ihj4dVBXMPg', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Mountain', 'Tadasana', 'https://www.youtube.com/embed/NYhH8Gr35cI', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Chair', 'Utkatasana', 'https://www.youtube.com/embed/ySafTekJ3Ls', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Tree', 'Vrksasana', 'https://www.youtube.com/embed/yVE4XXFFO70', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Eagle', 'Garudasana', 'https://www.youtube.com/embed/DSfmZHa14uI', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Hand To Big Toe In Front', 'Utthita Hasta Padangusthasana D', 'https://www.youtube.com/embed/INtjr2jjtmU', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('High Plank', 'Phalakasana', 'https://www.youtube.com/embed/6qg3r4zZE_k', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Low Plank', 'Chaturanga Dandasana', 'https://www.youtube.com/embed/3vzTYq4BX68', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Upward Facing Dog', 'Urdhva Mukha Svanasana', 'https://www.youtube.com/embed/tbh0qyLJRaI', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Cobra', 'Bhujangasana', 'https://www.youtube.com/embed/n6jrC6WeF84', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Revolved Triangle', 'Parivrtta Trikonasana', 'https://www.youtube.com/embed/sX11hp65x14', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Low Lunge', 'Anjaneyasana', 'https://www.youtube.com/embed/MjiC4mGTnTw', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Runners Lunge', 'Utthita Ashwa Sanchalanasana', 'https://www.youtube.com/embed/OfJl_jhJcWw', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('High Lunge', 'Ashta Chandrasana', 'https://www.youtube.com/embed/eXupg3oNGJY', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Revolved Lunge', 'Parivrtta Utthita Ashwa Sanchalanasana', 'https://www.youtube.com/embed/tOF3uikpFZ4', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Wide Legged Forward Fold', 'Prasarita Padottanasana', 'https://www.youtube.com/embed/F7you4Sw1o0', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Half Lotus', 'Ardha Padmasana', 'https://www.youtube.com/embed/b66GQ4-O8_8', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Lotus', 'Padmasana', 'https://www.youtube.com/embed/V8zksuBdU6A', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Figure Four', 'Eka Pada Utkatasana', 'https://www.youtube.com/embed/7PRDTBL2LEI', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Staff', 'Dandasana', 'https://www.youtube.com/embed/sXz0OCjO3p4', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Seated Forward Fold', 'Paschimottanasana', 'https://www.youtube.com/embed/CNRLcEPJdIU', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Table Top', 'Bharmanasana', 'https://www.youtube.com/embed/PGAntbDQ6Xg', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Reverse Table Top', 'Ardha Purvottanasana', 'https://www.youtube.com/embed/L9bdozB8MFw', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Sphinx', 'Salamba Bhujangasana', 'https://www.youtube.com/embed/F5JVnU-hQ44', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Head To Knee', 'Janu Sirsasana', 'https://www.youtube.com/embed/dIvn6YyIaWc', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Boat', 'Navasana', 'https://www.youtube.com/embed/8KsyQvwi85Q', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Bridge', 'Setu Bandha Sarvangasana', 'https://www.youtube.com/embed/NnbvPeAIhmA', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Wheel', 'Chakrasana', 'https://www.youtube.com/embed/4F4lTh09Z5E', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Corpse', 'Savasana', 'https://www.youtube.com/embed/eSeRjoolN2A', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Bound Angle', 'Baddha Konasana', 'https://www.youtube.com/embed/B6tb4TncKhY', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Reclining Bound Angle', 'Supta Baddha Konasana', 'https://www.youtube.com/embed/VNx6l5RmJhQ', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Crow', 'Bakasana', 'https://www.youtube.com/embed/DgvjvwPGLPY', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Eight Angle', 'Astavakrasana', 'https://www.youtube.com/embed/3LFuaEkPdP4', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Handstand', 'Adho Mukha Vrksasana', 'https://www.youtube.com/embed/9YX4nlXuqso', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Headstand', 'Sirsasana', 'https://www.youtube.com/embed/V1HbXt5ZRlg', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Forearm Stand', 'Pincha Mayurasana', 'https://www.youtube.com/embed/M9Xna6MKuNY', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Seated Wide Legged Forward Fold', 'Upavistha Konasana', 'https://www.youtube.com/embed/SpOwFLqRflc', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Happy Baby', 'Ananda Balasana', 'https://www.youtube.com/embed/Ppku7i3ypGM', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Supine Twist', 'Supta Matsyendrasana', 'https://www.youtube.com/embed/ezyMaQEaVaI', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Locust', 'Salabhasana', 'https://www.youtube.com/embed/0kxczNm1xF4', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Bow', 'Dhanurasana', 'https://www.youtube.com/embed/FCuSE4oS9xc', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Camel', 'Ustrasana', 'https://www.youtube.com/embed/AigVwIFvmAQ', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Half Pigeon', 'Eka Pada Rajakapotasana', 'https://www.youtube.com/embed/0_zPqA65Nok', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Dolphin', 'Catur Svanasana', 'https://www.youtube.com/embed/6w4ZoSuBDCg', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Cow Face', 'Gomukhasana', 'https://www.youtube.com/embed/-qbPrlf1oxE', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Backbend', 'Anuvittasana', 'https://www.youtube.com/embed/FH29E2EHoPo', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Shoulderstand', 'Sarvangasana', 'https://www.youtube.com/embed/SOHsI7XI0mg', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Plow', 'Halasana', 'https://www.youtube.com/embed/wDMoau3EDC8', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Three Legged Dog', 'Tri Pada Adho Mukha Svanasana', 'https://www.youtube.com/embed/PPUAjosakvY', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Wild Thing', 'Camatkarasana', 'https://www.youtube.com/embed/dSQF5O3dLOk', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Side Plank', 'Vasisthasana', 'https://www.youtube.com/embed/krrxMqVQPCU', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Half Splits', 'Ardha Hanumanasana', 'https://www.youtube.com/embed/F9V9g87IVXc', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Front Split', 'Hanumanasana', 'https://www.youtube.com/embed/DQlLTrMY5KI', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Middle Split', 'Samakonasana', 'https://www.youtube.com/embed/bgJeNfLahDQ', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Upward Plank', 'Purvottanasana', 'https://www.youtube.com/embed/6jXfLZzzW6M', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Side Crow', 'Parsva Bakasana', 'https://www.youtube.com/embed/acFCTDIhBjU', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Flying Splits', 'Koundinyasana II', 'https://www.youtube.com/embed/D8e6mLJDJ10&t=366s', 'advanced');
insert into poses (name, sanskrit, demo, difficulty) values ('Childs Pose', 'Balasana', 'https://www.youtube.com/embed/eqVMAPM00DM', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Hand To Big Toe', 'Utthita Hasta Padangusthasana', 'https://www.youtube.com/embed/M3Nz4enOL6Y', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Garland', 'Malasana', 'https://www.youtube.com/embed/IXpJEqssze8', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Half Moon', 'Ardha Chandrasana', 'https://www.youtube.com/embed/EriPRTk1ly0', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Dancers', 'Natarajasana', 'https://www.youtube.com/embed/TXNgRNsqcPo', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Standing Splits', 'Urdhva Prasarita Eka Padasana', 'https://www.youtube.com/embed/f7su7pc4CHg', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Extended Mountain', 'Utthita Tadasana', 'https://www.youtube.com/embed/B7J6pX20Rks', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Puppy', 'Uttana Shishosana', 'https://www.youtube.com/embed/mytWLo8fHbw', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Cat', 'Marjaryasana', 'https://www.youtube.com/embed/y39PrKY_4JM', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Cow', 'Bitilasana', 'https://www.youtube.com/embed/y39PrKY_4JM', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Revolved Chair', 'Parivrtta Utkatasana', 'https://www.youtube.com/embed/rAbabfidKiw', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Easy Seat', 'Sukhasana', 'https://www.youtube.com/embed/zLvJD7iKVhw', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Constructive Rest', 'Savasana Variation Bent Legs', 'https://www.youtube.com/embed/jmJbcS-Ux2U', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Lizard', 'Utthan Pristhasana', 'https://www.youtube.com/embed/-6MGjYmHdYQ', 'intermediate');
insert into poses (name, sanskrit, demo, difficulty) values ('Goddess', 'Utkata Konasana', 'https://www.youtube.com/embed/wgXefCprLm0', 'beginner');
insert into poses (name, sanskrit, demo, difficulty) values ('Pyramid', 'Parsvottanasana', 'https://www.youtube.com/embed/LTe3CO7Vtxs', 'beginner');