insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Warrior I'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Halfway Lift'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Table Top'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Handstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Half Pigeon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Dolphin'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Three Legged Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Wild Thing'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Flying Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'Warrior III'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'Humble Warrior'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior I'), (select id from poses where name = 'Pyramid'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Reverse Warrior'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Extended Side Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Standing Wide Legged Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Half Moon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior II'), (select id from poses where name = 'Goddess'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Reverse Warrior'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Half Moon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Standing Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Warrior III'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Extended Side Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Half Moon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Humble Warrior'), (select id from poses where name = 'Warrior I'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Humble Warrior'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Humble Warrior'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Humble Warrior'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Reverse Warrior'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Extended Side Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Revolved Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Standing Wide Legged Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Triangle'), (select id from poses where name = 'Half Moon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Reverse Warrior'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Half Moon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Halfway Lift'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Handstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Standing Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Handstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Standing Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Halfway Lift'), (select id from poses where name = 'Pyramid'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Tree'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Eagle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Hand To Big Toe In Front'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Figure Four'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Backbend'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Standing Hand To Big Toe'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Dancers'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Mountain'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Eagle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Standing Figure Four'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Standing Backbend'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Side Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Revolved Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Chair'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Eagle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Standing Hand To Big Toe In Front'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Standing Figure Four'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Dancers'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Tree'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Eagle'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Eagle'), (select id from poses where name = 'Standing Hand To Big Toe In Front'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Eagle'), (select id from poses where name = 'Standing Figure Four'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Warrior III'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Tree'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Eagle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Standing Figure Four'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Standing Hand To Big Toe'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Dancers'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Low Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Flying Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Plank'), (select id from poses where name = 'Table Top'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'Upward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'Cobra'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'Sphinx'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'Locust'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Plank'), (select id from poses where name = 'Bow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Upward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Sphinx'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Locust'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Bow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cobra'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from poses where name = 'Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from poses where name = 'Revolved Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from poses where name = 'Pyramid'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Lunge'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Lunge'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Lunge'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Lunge'), (select id from poses where name = 'Half Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Low Lunge'), (select id from poses where name = 'Front Split'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Halfway Lift'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Revolved Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Half Pigeon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Runners Lunge'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Warrior I'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Warrior III'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Triangle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Revolved Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'High Lunge'), (select id from poses where name = 'Goddess'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Headstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Seated Wide Legged Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Middle Split'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from poses where name = 'Goddess'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Lotus'), (select id from poses where name = 'Lotus'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Lotus'), (select id from poses where name = 'Bound Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Lotus'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Lotus'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Tree'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Eagle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Standing Hand To Big Toe In Front'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Standing Hand To Big Toe'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Seated Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Reverse Table Top'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Head To Knee'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Boat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Cow Face'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Staff'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Seated Forward Fold'), (select id from poses where name = 'Staff'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Seated Forward Fold'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Seated Forward Fold'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Dolphin'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Puppy'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Cat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Cow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Table Top'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from poses where name = 'Upward Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = 'Upward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = 'Cobra'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = 'Dolphin'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = 'Childs Pose'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Sphinx'), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Head To Knee'), (select id from poses where name = 'Seated Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Head To Knee'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Head To Knee'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Boat'), (select id from poses where name = 'Staff'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Boat'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Boat'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bridge'), (select id from poses where name = 'Wheel'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bridge'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bridge'), (select id from poses where name = 'Reclining Bound Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bridge'), (select id from poses where name = 'Constructive Rest'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Wheel'), (select id from poses where name = 'Constructive Rest'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Wheel'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Happy Baby'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Supine Twist'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Shoulderstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Constructive Rest'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Corpse'), (select id from poses where name = 'Reclining Bound Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Half Lotus'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Lotus'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Seated Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Staff'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Reverse Table Top'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Reclining Bound Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Cow Face'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bound Angle'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reclining Bound Angle'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reclining Bound Angle'), (select id from poses where name = 'Happy Baby'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Reclining Bound Angle'), (select id from poses where name = 'Supine Twist'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Locust'), (select id from poses where name = 'Cobra'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Locust'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Locust'), (select id from poses where name = 'Bow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Camel'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bow'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Bow'), (select id from poses where name = 'Locust'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Crow'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Crow'), (select id from poses where name = 'Low Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Crow'), (select id from poses where name = 'Garland'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Crow'), (select id from poses where name = 'Headstand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Eight Angle'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Handstand'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Handstand'), (select id from poses where name = 'Low Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Headstand'), (select id from poses where name = 'Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Headstand'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Headstand'), (select id from poses where name = 'Standing Wide Legged Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Headstand'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Forearm Stand'), (select id from poses where name = 'Dolphin'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Forearm Stand'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Seated Wide Legged Forward Fold'), (select id from poses where name = 'Seated Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Seated Wide Legged Forward Fold'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Happy Baby'), (select id from poses where name = 'Supine Twist'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Happy Baby'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Happy Baby'), (select id from poses where name = 'Reclining Bound Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Supine Twist'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Pigeon'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Pigeon'), (select id from poses where name = 'Cow Face'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Pigeon'), (select id from poses where name = 'Three Legged Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Pigeon'), (select id from poses where name = 'Head To Knee'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Dolphin'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Dolphin'), (select id from poses where name = 'Forearm Stand'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cow Face'), (select id from poses where name = 'Seated Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Cow Face'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Backbend'), (select id from poses where name = 'Extended Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Backbend'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Shoulderstand'), (select id from poses where name = 'Plow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Shoulderstand'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Plow'), (select id from poses where name = 'Corpse'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Warrior I'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Warrior II'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Extended Side Angle'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Runners Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'High Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Half Pigeon'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Wild Thing'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Side Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Flying Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from poses where name = 'Lizard'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Wild Thing'), (select id from poses where name = 'Wheel'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Wild Thing'), (select id from poses where name = 'Three Legged Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Side Plank'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Side Plank'), (select id from poses where name = 'Wild Thing'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Splits'), (select id from poses where name = 'Low Lunge'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Splits'), (select id from poses where name = 'Front Split'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Front Split'), (select id from poses where name = 'Half Splits'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Front Split'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Middle Split'), (select id from poses where name = 'Seated Wide Legged Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Middle Split'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Upward Plank'), (select id from poses where name = 'Staff'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Upward Plank'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Side Crow'), (select id from poses where name = 'Revolved Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Side Crow'), (select id from poses where name = 'Low Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Flying Splits'), (select id from poses where name = 'Low Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Flying Splits'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Childs Pose'), (select id from poses where name = 'Downward Facing Dog'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Childs Pose'), (select id from poses where name = 'Table Top'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Childs Pose'), (select id from poses where name = 'Puppy'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe'), (select id from poses where name = 'Standing Hand To Big Toe In Front'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Standing Hand To Big Toe'), (select id from poses where name = 'Tree'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'Standing Forward Fold'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'Mountain'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'Chair'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'High Plank'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'Crow'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Garland'), (select id from poses where name = 'Easy Seat'));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = 'Half Moon'), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));
insert into after_poses (pose_id, after_pose_id) values ((select id from poses where name = ''), (select id from poses where name = ''));