insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cobra'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Sphinx'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wheel'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Camel'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Shoulderstand'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Plow'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Plank'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Puppy'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cat'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cow'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Easy Seat'), (select id from bodyparts where name = 'neck'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Humble Warrior'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Eagle'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wheel'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Handstand'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bow'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Dolphin'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cow Face'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Shoulderstand'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Plow'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wild Thing'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Side Plank'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Plank'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Puppy'), (select id from bodyparts where name = 'shoulders'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Humble Warrior'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Halfway Lift'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cobra'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Staff'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Seated Forward Fold'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Sphinx'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Head To Knee'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bridge'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wheel'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Corpse'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Seated Wide Legged Forward Fold'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Happy Baby'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Supine Twist'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Locust'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bow'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Camel'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Backbend'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Plow'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Childs'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Garland'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Extended Mountain'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Puppy'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cat'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cow'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Chair'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Constructive Rest'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Pyramid'), (select id from bodyparts where name = 'back'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Low Lunge'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Runners Lunge'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'High Lunge'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Lotus'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Lotus'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bound Angle'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reclining Bound Angle'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Seated Wide Legged Forward Fold'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Happy Baby'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Pigeon'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cow Face'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Splits'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Front Split'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Middle Split'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Flying Splits'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Childs Pose'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Garland'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Splits'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Lizard'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Goddess'), (select id from bodyparts where name = 'hips'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Downward Facing Dog'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Warrior I'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Warrior II'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Warrior III'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Warrior'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Humble Warrior'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Triangle'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Forward Fold'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Halfway Lift'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Mountain'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Chair'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Tree'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Eagle'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Hand To Big Toe In Front'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Triangle'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Low Lunge'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Runners Lunge'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'High Lunge'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Lunge'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Wide Legged Forward Fold'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Staff'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Seated Forward Fold'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Head To Knee'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bridge'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wheel'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Seated Wide Legged Forward Fold'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Happy Baby'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Dolphin'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Three Legged Dog'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wild Thing'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Side Plank'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Splits'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Front Split'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Middle Split'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Plank'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Hand To Big Toe'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Garland'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Moon'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Dancers'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Splits'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Chair'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Lizard'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Goddess'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Pyramid'), (select id from bodyparts where name = 'legs'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Facing Dog'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Cobra'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Sphinx'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bridge'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wheel'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Locust'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Bow'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Camel'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Backbend'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Wild Thing'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Plank'), (select id from bodyparts where name = 'chest'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Warrior III'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Triangle'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Extended Side Angle'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Chair'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Eagle'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'High Plank'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Low Plank'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Figure Four'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Table Top'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Reverse Table Top'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Boat'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Crow'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Eight Angle'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Handstand'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Headstand'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Forearm Stand'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Standing Backbend'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Side Plank'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Upward Plank'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Side Crow'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Flying Splits'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Half Moon'), (select id from bodyparts where name = 'core'));
insert into pose_bodyparts (pose_id, bodypart_id) values ((select id from poses where name = 'Revolved Chair'), (select id from bodyparts where name = 'core'));
